[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

# 处理API请求和动态路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/heroes/*"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/heroes"
  to = "/.netlify/functions/entry"
  status = 200

# 最后的回退规则
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
